// mutagen-bridge - Mutagen bridge for the mo2_mcp plugin
// Copyright (c) 2026 Aaronavich
// Licensed under the MIT License. See LICENSE for details.

using System.Collections.Concurrent;
using System.Reflection;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;

namespace MutagenBridge;

/// <summary>
/// v2.6.0 Phase 3 — per-plugin record enumerator. Replaces the hand-rolled
/// Python <c>esp_reader.py</c> that was parsing raw <c>&lt;I</c> FormID bytes
/// out of plugin files. Mutagen's <c>FormKey</c> is the source of truth, so
/// origin resolution + ESL FormID compaction are automatic — every FormID
/// emitted matches what xEdit displays for the same record.
///
/// Emits <see cref="ScannedRecord"/> entries with only <c>type</c>,
/// <c>formid</c>, and <c>edid</c>. Aggregate response size matters when
/// scanning a 3000+ plugin Skyrim modlist (~2.9M records); minimal-by-default
/// keeps batched scans tractable.
/// </summary>
public class IndexScanner
{
    /// <summary>
    /// Scan every plugin in the request. One <see cref="CreateFromBinaryOverlay"/>
    /// per plugin; per-plugin try/catch isolates failures so a single corrupt
    /// file doesn't void the batch.
    /// </summary>
    public ScanResponse Scan(ScanRequest request)
    {
        var response = new ScanResponse { Success = true };

        if (request.Plugins.Count == 0)
        {
            response.Success = false;
            response.Error = "plugins list is empty.";
            return response;
        }

        foreach (var path in request.Plugins)
        {
            response.Plugins.Add(ScanOne(path));
        }

        // Top-level success requires at least one plugin scan to succeed.
        // Per-plugin errors are surfaced inline so partial failures don't
        // void successful scans elsewhere in the batch.
        if (!response.Plugins.Any(p => p.Error == null))
        {
            response.Success = false;
            response.Error = "All plugins in the batch failed to scan.";
        }

        return response;
    }

    private static ScannedPlugin ScanOne(string path)
    {
        var result = new ScannedPlugin
        {
            PluginPath = path,
            PluginName = string.IsNullOrEmpty(path) ? "" : Path.GetFileName(path),
        };

        if (string.IsNullOrEmpty(path))
        {
            result.Error = "plugin_path is empty.";
            return result;
        }
        if (!File.Exists(path))
        {
            result.Error = $"Plugin not found: {path}";
            return result;
        }

        try
        {
            using var mod = SkyrimMod.CreateFromBinaryOverlay(path, SkyrimRelease.SkyrimSE);

            result.Masters = mod.ModHeader.MasterReferences
                .Select(m => m.Master.FileName.String)
                .ToList();
            // SkyrimModHeader.HeaderFlag values per Mutagen 0.53.1:
            //   Master = 0x01, Localized = 0x80, Small = 0x200.
            // "Small" is Mutagen's name for the ESL/Light flag.
            result.IsMaster = mod.ModHeader.Flags.HasFlag(SkyrimModHeader.HeaderFlag.Master);
            result.IsLight = mod.ModHeader.Flags.HasFlag(SkyrimModHeader.HeaderFlag.Small);
            result.IsLocalized = mod.ModHeader.Flags.HasFlag(SkyrimModHeader.HeaderFlag.Localized);

            foreach (var record in mod.EnumerateMajorRecords())
            {
                result.Records.Add(new ScannedRecord
                {
                    Type = RecordTypeCode(record),
                    FormId = FormIdHelper.Format(record.FormKey),
                    EditorId = record.EditorID,
                });
            }
            result.RecordCount = result.Records.Count;
        }
        catch (Exception ex)
        {
            result.Error = $"Scan failed for {Path.GetFileName(path)}: {ex.Message}";
        }

        return result;
    }

    /// <summary>
    /// Cache of registration-type → 4-letter Bethesda record code.
    /// Reflection is hit once per concrete registration class (~200 keys
    /// across all Skyrim record types); subsequent calls are dictionary
    /// lookups.
    /// </summary>
    private static readonly ConcurrentDictionary<Type, string> _typeCodeCache = new();

    /// <summary>
    /// Pull the Bethesda 4-letter record signature off Mutagen's per-record
    /// registration class. The `*_Registration` classes are internal partials
    /// generated by Loqui (e.g. `MusicType_Registration`) with a public
    /// static readonly RecordType field named <c>TriggeringRecordType</c>.
    ///
    /// Reflection on the runtime registration type bypasses `internal` and
    /// gives us coverage for every Major record type without a hand-maintained
    /// switch. Falls back to the C# class name for the rare record without a
    /// canonical 4-letter code (none in Skyrim AFAIK, but safe default).
    /// </summary>
    private static string RecordTypeCode(IMajorRecordGetter record)
    {
        var regType = record.Registration.GetType();
        return _typeCodeCache.GetOrAdd(regType, t =>
        {
            try
            {
                var field = t.GetField(
                    "TriggeringRecordType",
                    BindingFlags.Public | BindingFlags.Static);
                if (field?.GetValue(null) is RecordType rt && !string.IsNullOrEmpty(rt.Type))
                    return rt.Type;
            }
            catch
            {
                // Fall through to class-name fallback.
            }

            var name = record.Registration.ClassType.Name;
            if (name.EndsWith("Getter", StringComparison.Ordinal))
                name = name[..^6];
            return name.ToUpperInvariant();
        });
    }
}
